name: client

on:
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: install dependencies
      working-directory: client
      run: |
        npm install
      env:
        CI: true

    - name: build package
      working-directory: client
      run: |
        npm run build
      env:
        CI: true

    - uses: actions/upload-artifact@v1
      if: success()
      with:
          name: client
          path: client/dist
